# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87088-ECOMMERCE-DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f1498979585c4a0e9abe4eb522c01a2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0a38d51b21ff4ad4b962b0ed92190008 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f1498979585c4a0e9abe4eb522c01a2e }}/ecommerce:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87088-ECOMMERCE-DEV'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cbade6d9257b4f0699d7616ceeb0b407 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f1498979585c4a0e9abe4eb522c01a2e }}/ecommerce:${{ github.sha }}'